# main.workflow

on:
  push:
    branches:
      - '*' # 将 '*' 替换为您希望覆盖的分支名称
  pull_request:
    branches:
      - '*' # 将 '*' 替换为您希望覆盖的分支名称

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show java version
        run: java -version
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          codecov_token: ${{ env.CODECOV_TOKEN }}